dist: xenial
language: ruby
rvm:
- 2.4.3
env:
  global:
    - FRAMEWORK_BRANCH=main
jobs:
  include:
    - stage: deploy
      if: branch = main OR repo =~ /-internal/
      before_install:
      - echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
      - git submodule add -b $FRAMEWORK_BRANCH https://github.com/NetAppDocs/jekyll dependencies/jekyll
      - gem update --system && gem install bundler && gem update bundler
      - if [[ -z "$DEPLOY_BRANCH" ]]; then export DEPLOY_BRANCH=gh-pages; fi
      - cp -rl dependencies/jekyll/search.html ./api/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ api\/search\.html/g' ./api/search.html
      - cp -rl dependencies/jekyll/search.html ./concepts/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ concepts\/search\.html/g' ./concepts/search.html
      - cp -rl dependencies/jekyll/search.html ./esds/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ esds\/search\.html/g' ./esds/search.html
      - cp -rl dependencies/jekyll/search.html ./hardware/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ hardware\/search\.html/g' ./hardware/search.html
      - cp -rl dependencies/jekyll/search.html ./setup/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ setup\/search\.html/g' ./setup/search.html
      - cp -rl dependencies/jekyll/search.html ./storage/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ storage\/search\.html/g' ./storage/search.html
      - cp -rl dependencies/jekyll/search.html ./try/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ try\/search\.html/g' ./try/search.html
      - mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
      - sudo apt-get -y install graphicsmagick graphicsmagick-libmagick-dev-compat libmagickwand-dev
      script:
      - if [[ ! -z "$FEATURE_FLAG" ]]; then bundle exec rake buildAll; fi
      - mkdir -p /tmp/output && bundle exec jekyll build --trace --destination /tmp/output --config _config.yml,project.yml
      - touch /tmp/output/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        keep_history: false
        local_dir: /tmp/output
        target_branch: $DEPLOY_BRANCH
        verbose: true
        on:
          all_branches: true
    - state: i18n
      if: branch = main OR repo =~ /-internal/
      before_install:
      - echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc && chmod 600 ~/.netrc
      - git submodule add https://github.com/NetAppDocs/jekyll-harmony dependencies/jekyll-harmony
      - gem update --system && gem install bundler && gem update bundler
      install:
      - cd dependencies/jekyll-harmony
      - bundle install --jobs=3 --retry=3
      - bundle exec rake install
      - cd -
      script:
      - if [[ ! -z "$HARMONY_FLAG" ]]; then i18n-translate; fi
