---
sidebar: sidebar
permalink: element-legal.html
keywords: copyrights, notice, trademarks, patents, privacy, open source
summary: Legal notices provide access to copyright statements, trademarks, patents, and more.
---

= Legal notices
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
Legal notices provide access to copyright statements, trademarks, patents, and more.

== Copyright

http://www.netapp.com/us/legal/copyright.aspx[^]

== Trademarks

NETAPP, the NETAPP logo, and the marks listed on the NetApp Trademarks page are trademarks of NetApp, Inc. Other company and product names may be trademarks of their respective owners.

http://www.netapp.com/us/legal/netapptmlist.aspx[^]

== Patents

A current list of NetApp owned patents can be found at:

https://www.netapp.com/us/media/patents-page.pdf[^]

== Privacy policy

https://www.netapp.com/us/legal/privacypolicy/index.aspx[^]

== Open source

Notice files provide information about third-party copyright and licenses.

* link:./media/mgmt_2.17.56_notice.pdf[Notice for Management Services 2.17.56^]
* link:./media/mgmt-217.pdf[Notice for Management Services 2.17.52^]
* link:./media/mgmt-216.pdf[Notice for Management Services 2.16^]
* link:./media/mgmt-214.pdf[Notice for Management Services 2.14^]
* link:./media/mgmt-213.pdf[Notice for Management Services 2.13^]
