---
permalink: hardware-d/task_sf_h410s_prepare_for_node_replacement.html
sidebar: sidebar
keywords: 
summary: 'You must remove the failed storage node correctly from the cluster in the NetApp Element software UI before you install the replacement node. You can do this without causing any service interruption. You must obtain the serial number of the failed storage node from the Element UI and match it with the serial number on the sticker at the back of the node.'
---
= Prepare to replace H410S node in the cluster
:icons: font
:imagesdir: ../media/

[.lead]
You must remove the failed storage node correctly from the cluster in the NetApp Element software UI before you install the replacement node. You can do this without causing any service interruption. You must obtain the serial number of the failed storage node from the Element UI and match it with the serial number on the sticker at the back of the node.

. In the Element UI, select *Cluster* > *Drives*.
. Remove the drives from the node using one of the following methods:
+
|===
| Option| Steps
a|
To remove individual drives
a|

 .. Click *Actions* for the drive you want to remove.
 .. Click *Remove*.

a|
To remove multiple drives
a|

 .. Select all the drives you want to remove, and click *Bulk Actions*.
 .. Click *Remove*.

+
|===

. Click *Cluster* > *Nodes*.
. Note the serial number (service tag) of the failed node. You will take the serial number you noted to your chassis and match it with the serial number on the sticker at the back of the node.
. After you note the serial number, remove the node from the cluster as follows:
 .. Click the *Actions* button for the node you want to remove.
 .. Click *Remove*.
