---
sidebar: sidebar
permalink: upgrade/concept_element_upgrade_overview.html
summary: This overview introduces how to perform upgrades for a NetApp HCI or SolidFire Element storage system.
keywords: netapp, solidfire upgrade, VCP upgrade, element upgrade, vSphere upgrade
---

= Upgrades overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: solidfire, cloud, onprem, documentation, help

[.lead]
The content in this section introduces recommended upgrade sequences for components in a NetApp [.line-through]#HCI system or# SolidFire all-flash storage system. ​

== System upgrade sequences

System upgrade sequences content describes the tasks that are needed to complete a NetApp [.line-through]#HCI system or# SolidFire all-flash storage system upgrade. Ideally these procedures are performed as part of the larger upgrade sequence and not in isolation. If a component-based upgrade or update is needed, see the procedure prerequisites to ensure additional complexities are addressed.

Use the following sequence to upgrade your NetApp SolidFire all-flash storage system for Element 12.3:

* link:task_sf_upgrade_all.html[Upgrade your NetApp SolidFire all-flash storage system for Element 12.3].

== vSphere upgrade sequences including Element Plug-in for vCenter Server

vSphere upgrade sequences including Element Plug-in for vCenter Server content describes additional pre- and post-upgrade steps required to re-install the Element Plug-in for vCenter Server.

Use the following sequence to upgrade your vSphere components in a NetApp SolidFire all-flash storage system with Element Plug-in for vCenter Server:

* link:task_sf_upgrade_all_vsphere.html[Upgrade your vSphere components for a NetApp SolidFire storage system with the Element Plug-in for vCenter Server].

[discrete]
== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element documentation^]
