---
sidebar: sidebar
permalink: upgrade/concept_element_upgrade_overview.html
summary: You can keep your SolidFire Element storage system up-to-date after deployment by upgrading all NetApp storage components.
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade
---

= Upgrade overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: solidfire, cloud, onprem, documentation, help

[.lead]
You can keep your SolidFire Element storage system up-to-date after deployment by sequentially upgrading all NetApp storage components.

These components include management services, HealthTools, NetApp Hybrid Cloud Control, Element software, management node, and (depending on your installation) the Element Plug-in for vCenter Server.

The <<sys_upgrade,system upgrade sequence>> content describes the tasks that are needed to complete a SolidFire all-flash storage system upgrade. Ideally these procedures are performed as part of the larger upgrade sequence and not in isolation. If a component-based upgrade or update is needed, see the procedure prerequisites to ensure additional complexities are addressed.

The link:task_sf_upgrade_all_vsphere.html[vSphere upgrade sequence] including Element Plug-in for vCenter Server content describes additional pre- and post-upgrade steps required to re-install the Element Plug-in for vCenter Server.

.What you'll need

* You are running management node 11.3 or later. Newer versions of the management node have a modular architecture that provides individual services.
+
TIP: To check the version, log in to your management node and view the Element version number in the login banner. If you do not have 11.3, see link:task_hcc_upgrade_management_node.html[Upgrade your management node].

* You have upgraded your management services to at least version 2.1.326.
+
Upgrades using NetApp Hybrid Cloud Control are not available in earlier service bundle versions.

* You have ensured that the system time on all nodes is synced and that NTP is correctly configured for the storage cluster and nodes. Each node must be configured with a DNS nameserver in the per-node web UI (`https://[IP address]:442`) with no unresolved cluster faults related to time skew.

* For Element software and storage firmware upgrades, you have scheduled sufficient time to perform your upgrade. The upgrade process time varies depending on the Element software version and firmware updates.
+
[cols=5*,options="header",cols="30,14,14,12,30"]
|===
|Storage Node |Current Element software version |Approximate software and firmware install time per node^1^ |Approximate data synchronize time per node^2^ |Approximate total upgrade time per node

|All SolidFire and H-series nodes with up-to-date firmware	|12.x	|15 minutes	| 10 to 15 minutes |20 to 30 minutes
|H610S and H410S	|12.x	|6o minutes	|30 to 60 minutes |90 to 120 minutes
|H610S	| 11.7 and earlier |90 minutes | 40 to 70 minutes |130 to 160 minutes
You must also https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure[perform a complete node shutdown and power disconnect^] for each H610S node.
|===
+
^1^For a complete matrix of firmware and driver firmware for your hardware, see this https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software[KB article^] (login required).
+
^2^The data synchronization time increases when clusters with a heavier write IOPS load combined with a longer firmware update time. 

== [[sys_upgrade]]System upgrade sequence

You can use the following sequence to upgrade your NetApp SolidFire all-flash storage system for Element 12.3.x.

.Steps

. link:task_hcc_update_management_services.html[Update management services from Hybrid Cloud Control].
+
IMPORTANT: If you are updating management services to version 2.16 or later and you are running a management node 11.3 to 11.8, you will need to increase your management node VM's RAM prior to updating management services.
+
IMPORTANT: You must update to the latest management services bundle before upgrading your Element software.

. link:task_upgrade_element_latest_healthtools.html[(Optional) Upgrade to the latest HealthTools].
+
NOTE: Upgrading HealthTools is only required if the management node and Element software you are running is 11.1 or earlier. HealthTools are not required for performing Element upgrades using NetApp Hybrid Cloud Control.

. link:task_hcc_upgrade_element_prechecks.html[Run Element storage health checks prior to upgrading storage].
. link:task_hcc_upgrade_element_software.html[Upgrade your Element software and storage firmware].
. link:task_hcc_upgrade_storage_firmware.html[(Optional) Upgrade your Element storage firmware only].
+
NOTE: You might perform this task when a new storage firmware upgrade becomes available outside of a major release.

. link:task_hcc_upgrade_management_node.html[(Optional) Upgrade your management node].
+
NOTE: Upgrading the management node operating system is no longer required to upgrade Element software on the storage cluster. If the management node is version 11.3 or higher, you can simply upgrade the management services to the latest version to perform Element upgrades using NetApp Hybrid Cloud Control. Follow the management node upgrade procedure for your scenario if you would like to upgrade the management node operating system for other reasons, such as security remediation.

. link:task_vcp_upgrade_plugin.html[Upgrade your Element Plug-in for vCenter Server].

[discrete]
== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
