---
permalink: hardware/task_rtfi_process.html
sidebar: sidebar
keywords:
summary:
---

= Perform the RTFI process
:icons: font
:imagesdir: ../media/

[.lead]
You can begin the Return To Factory Install (RTFI) process by interacting with the node through text console prompts that appear before the system boots.

WARNING: The RTFI process is data destructive and securely erases all data and configuration details from the node and installs a new operating system. Verify that the node used for the RTFI process is not active as part of a cluster.

The RTFI process performs the following high-level operations:

. Starts the installation after user confirmation and validates the image.
. Unlocks all drives on a node.
. Validates and flashes firmware.
. Checks hardware.
. Tests hardware.
. Secure erases all selected drives.
. Partitions root drive and creates file systems.
. Mounts and unpacks image.
. Configures host name, networking (Dynamic Host Configuration Protocol), default cluster configuration, and GRUB bootloader.
. Stops all services, collects logs, and reboots.

To configure your node once the RTFI process has successfully completed, see the user guide for your Element software version. After a node has successfully completed the RTFI process, it transitions to the available (unconfigured) state by default.

== Perform the RTFI process

Follow these steps to restore the Element software on your SolidFire node.

.Before you begin

* Verify that you have access to a console for the SolidFire node.
* The node on which you will perform the RTFI process is powered up and connected to a network.
* The node on which you will perform the RTFI process is not part of an active cluster.
* Access to bootable installation media that contains the image of the relevant Element software version for your configuration.
* Contact NetApp Support if you have any concerns before performing the RTFI process.

.Steps
. Connect a monitor and keyboard to the back of node, or connect to baseboard management controller (BMC) IP BUI and bring up the iKVM/HTML5 console from the *Remote Control* tab in BUI.
. Insert a USB key, with an appropriate image, in one of the two USB slots in the back of the node.
. Power on or Power Reset the node and during the boot-up process select *F11* to select Boot Device:
+
NOTE: The Boot Device screen goes by quickly, so press the *F11* key multiple times in quick succession.

. In the boot device selection menu, highlight the USB option.
+
The options that appear depend on the USB brand that you are using.
+
NOTE: If there are no USB devices listed, go into the BIOS, verify that the USB is listed in the boot order, reboot, and try again. If that does not resolve the issue, go into the BIOS, browse to the *Save and Exit* tab, select *Restore to Optimized Defaults*, accept and save the settings, and reboot.

. A list of the images that are on the highlighted USB device appear. Select the desired version and select enter to start the RTFI.

. At the initial prompt, you are notified that the process will remove all data from the node and that data is not recoverable after the process begins. Type *Yes* to begin.
+
WARNING: All data and configuration details will be permanently erased from the node after the process is initiated. If you elect not to proceed, you will be directed to the link:task_rtfi_options_menu.html[RTFI options menu].
+
NOTE: If you want to watch the console during the RTFI process, you can press the *ALT+F8* keys to toggle to the verbose mode console. Press *ALT+F7* to return to the primary GUI.

. Type *no* when prompted to perform extensive hardware tests unless you have a reason to suspect hardware failure or are directed to perform the tests by NetApp Support.
+
A message indicates that the RTFI process has finished. The system powers off.
. Remove all bootable installation media, if necessary, after the node powers off.
+
The node is now ready to be powered on and configured. See the https://docs.netapp.com/us-en/element-software/setup/concept_setup_overview.html[Element software set up storage^] documentation to configure a storage node.
+
If you encountered an error message during the RTFI process, see link:task_rtfi_options_menu.html[RTFI options menu].

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation/[NetApp SolidFire Resources Page^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[Documentation for earlier versions of NetApp SolidFire and Element products^]
