---
permalink: hardware/task_sf_isg_prepare_to_install.html
sidebar: sidebar
keywords: 
summary: 'Before you install your system, you must inventory the hardware that was shipped to you, and contact NetApp Support if any of the items are missing.'
---
= Prepare for installation
:icons: font
:imagesdir: ../media/

[.lead]
Before you install your system, you must inventory the hardware that was shipped to you, and contact NetApp Support if any of the items are missing.

You must provide the following at your site:

* Rack space for the system. You would install an H410S storage node in a two rack unit (2U), four-node chassis. An H610S node (or chassis) needs one rack unit (1U) rack space.
* Cables of the following types:
 ** SFP28/SFP+ direct-attach cables or transceivers
 ** CAT5e or higher cables with RJ45 connector
* A keyboard, video, mouse (KVM) switch to configure your system
* USB stick (optional)

. Unpack the contents of the boxes.
. Inventory the hardware you received.
+
If you are setting up a new 2U, four-node installation, the box includes the following hardware:

 ** Chassis
 ** Bezel
 ** Slide rail kit
 ** Drives
 ** Nodes
 ** Power cables (two per chassis)
*Note:* The hardware that is shipped to you is dependent on what you order. The above list is only an example of what you will find in the box. If you order H610S storage nodes, the drives will come installed in the chassis.
