---
sidebar: sidebar
permalink: hccstorage/task-hcc-activeiq.html
summary: You can monitor your cluster health with SolidFire Active IQ.
keywords: netapp, element, activeiq, active iq, cluster, performance
---

= Monitor performance, capacity, and cluster health with SolidFire Active IQ

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
By using SolidFire Active IQ, you can monitor the events, performance, and capacity of your clusters. You can access SolidFire Active IQ from the NetApp Hybrid Cloud Control Dashboard.

*Before you begin*

* You must have a NetApp Support account to take advantage of this service.
* You must have authorization to use management node REST APIs.
* You have deployed a management node running version 12.0 or later.
* Your cluster version is running NetApp Element software 12.0 or later.
* You have Internet access. The Active IQ collector service cannot be used from dark sites.


*About this task*
You can obtain continually updated historical views of cluster-wide statistics. You can set up notifications to alert you about specified events, thresholds, or metrics on a cluster so that they can be addressed quickly.

As part of your normal support contract, NetApp Support monitors this data and alerts you to potential system issues.

*Steps*

. Open a web browser and browse to the IP address of the management node. For example:
+
----
https://[management node IP address]
----
. Log in to NetApp Hybrid Cloud Control by providing the SolidFire all-flash storage cluster administrator credentials.
. From the Dashboard, select the menu on the upper right.
. Select *View Active IQ*.
+
. To learn about SolidFire Active IQ, from the Dashboard, select the menu icon on the upper right and select *Documentation*.
. From the SolidFire Active IQ interface, verify that the NetApp SolidFire all-flash storage nodes are reporting telemetry correctly to Active IQ:
.. If you have more than one SolidFire all-flash storage installation, select *Select a Cluster* and choose the cluster from the list.
.. In the left navigation pane, select *Nodes*.
. If a node or nodes are missing from the list, contact NetApp Support.

TIP: To view the number of storage resources, look at the Hybrid Cloud Control (HCC) Dashboard. See link:task-hcc-dashboard.html[Monitor storage resources with the HCC Dashboard].


[discrete]
== Find more information
* https://help.monitoring.solidfire.com[NetApp SolidFire Active IQ Documentation^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
