---
permalink: concepts/concept_solidfire_concepts_volume_snapshots_for_data_protection.html
sidebar: sidebar
keywords: 
summary: 'A volume snapshot is a point-in-time copy of a volume that you could later use to restore a volume to that specific time.'
---
= Volume snapshots for data protection
:icons: font
:imagesdir: ../media/

[.lead]
A volume snapshot is a point-in-time copy of a volume that you could later use to restore a volume to that specific time.

While snapshots are similar to volume clones, snapshots are simply replicas of volume metadata, so you cannot mount or write to them. Creating a volume snapshot also takes only a small amount of system resources and space, which makes snapshot creation faster than cloning.

You can replicate snapshots to a remote cluster and use them as a backup copy of the volume. This enables you to roll back a volume to a specific point in time by using the replicated snapshot; you can also create a clone of a volume from a replicated snapshot.

You can back up snapshots from a SolidFire cluster to an external object store, or to another SolidFire cluster. When you back up a snapshot to an external object store, you must have a connection to the object store that allows read/write operations.

You can take a snapshot of an individual volume or multiple for data protection.
