---
permalink: concepts/concept_solidfire_element_ug_encryption_at_rest.html
sidebar: sidebar
keywords:
summary: 'With SolidFire clusters, you can encrypt all data stored on the cluster.'
---
= Encryption at rest
:icons: font
:imagesdir: ../media/

[.lead]
With SolidFire clusters, you can encrypt all data stored on the cluster as it rests on drives to protect against physical drives from theft.

= Encryption at Rest (hardware)
All drives in storage nodes are capable of encryption leverage AES 256-bit encryption at the drive level. Each drive has its own encryption key, which is created when the drive is first initialized. When you enable the encryption feature, a cluster-wide password is created, and chunks of the password are then distributed to all nodes in the cluster. No single node stores the entire password. The password is then used to password-protect all access to the drives. The password is needed to unlock the drive and then not needed unless power is removed from the drive or the drive is locked.

Enabling the Encryption-At-Rest feature does not affect performance or efficiency on the cluster. Additionally, if an encryption-enabled drive or node is removed from the cluster with the Element API or Element UI, encryption at rest will be disabled on the drives. After the drive is removed, the drive can be secure erased by using the SecureEraseDrives API method. If a drive or node is forcibly removed from the cluster, the data remains protected by the cluster-wide password and the drive's individual encryption keys.

= Encryption at Rest (Software)

Another type of encryption at rest, Software Encryption at Rest enables all data written to the SSDs in a storage cluster to be encrypted. Software Encryption At Rest is available by default in all http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-sds-ig//GUID-F1BDD19F-AF33-4CDE-B67F-C5E17D4E6DE9.html[SolidFire Enterprise SDS nodes]. This provides a primary software layer of encryption in SolidFire Enterprise SDS nodes that do not include Self-Encrypting Drives (SEDs).

Both software and hardware-based encryption at rest can be used independently or in combination with one another.
