---
permalink: concepts/concept_rn_whats_new_element.html
sidebar: sidebar
keywords:
summary: NetApp periodically updates SolidFire and Element software to bring you new features, enhancements, and bug fixes. 
---
= What's new
:icons: font
:imagesdir: ../media/

[.lead]
NetApp periodically updates SolidFire and Element software to bring you new features, enhancements, and bug fixes. NetApp HCI 1.8P1 includes Element 12.2 for storage clusters.

* The <<Element 12.2>> section describes new features and updates in NetApp Element 12.2.
* The <<NetApp HCI 1.8P1>> section describes new features and updates in NetApp HCI version 1.8P1.


== Element 12.2
NetApp HCI 1.8P1 includes Element 12.2 for storage clusters. Element 12.2 introduces SolidFire Enterprise SDS, software encryption at rest, maintenance mode, enhanced volume access security, Fully Qualified Domain Name (FQDN) access to UIs, storage node firmware updates, and security updates.

=== SolidFire Enterprise SDS
Element 12.2 introduces SolidFire Enterprise SDS (eSDS). SolidFire eSDS provides the benefits of SolidFire scale out technology and NetApp Element software data services on the hardware of your choice that meets the reference configuration for SolidFire eSDS. https://review.docs.netapp.com/element-software_element_initial_amg/us-en/esds/concept_esds_overview.html[Get an overview of SolidFire eSDS^].

The following are new Element API methods related to SolidFire eSDS. (https://review.docs.netapp.com/element-software_element_initial_amg/us-en/esds-a/reference_esds_api_links.html[Element 12.2 API information for SolidFire eSDS] has more information):

* `GetLicenseKey`
* `SetLicenseKey`

=== Software encryption at rest
Element 12.2 introduces software encryption at rest, which you can enable when you create a storage cluster (and is enabled by default when you create a SolidFire Enterprise SDS storage cluster). This feature encrypts all data stored on the SSDs in the storage nodes and causes only a very small (~2%) performance impact on client IO.

The following are Element API methods related to software encryption at rest (the http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/home.html[Element API Reference Guide^] has more information):

* `CreateCluster`

=== Maintenance mode
Element 12.2 introduces maintenance mode, which enables you to take a storage node offline for maintenance such as software upgrades or host repairs, while preventing a full sync of all data. If one or more nodes need maintenance, you can minimize the I/O impact to the rest of the storage cluster by enabling maintenance mode for those nodes before you begin. You can use maintenance mode with both appliance nodes as well as SolidFire eSDS nodes.

=== Enhanced volume access security
You can now restrict volume access to certain initiators based on VLAN (virtual network) association. You can associate new or existing initiators with one or more virtual networks, restricting that initiator to iSCSI targets accessible via those virtual networks.

The following are updated Element API methods related to these security improvements (the http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/home.html[Element API Reference Guide^] has more information):

* `CreateInitiators`
* `ModifyInitiators`
* `AddAccount`
* `ModifyAccount`

=== Fully Qualified Domain Name (FQDN) access to UIs
Element 12.2 supports cluster web interface access using FQDNs. On Element 12.2 storage clusters, if you use the FQDN to access web user interfaces such as the Element web UI, per-node UI, or management node UI, you must first add a storage cluster setting to identify the FQDN used by the cluster. This setting enables the cluster to properly redirect a login session and facilitates better integration with external services like key managers and identity providers for multi-factor authentication. This feature requires management services version 2.15 or later. link:task_nde_access_ui_fqdn.html[Learn more^].

=== Storage node firmware updates
Element 12.2 includes firmware updates for storage nodes. http://docs.netapp.com/us-en/hci/docs/rn_relatedrn.html[Learn more^].

=== Security enhancements
Element 12.2 resolves security vulnerabilities for storage nodes and the management node. http://security.netapp.com/[Learn more^] about these security enhancements.

=== New SMART warning for failing drives
Element 12.2 now performs periodic health checks on SolidFire appliance drives using SMART health data from the drives. A drive that fails the SMART health check might be close to failure. If a drive fails the SMART health check, a new critical severity cluster fault appears: `Drive with serial: <serial number> in slot: <node slot><drive slot> has failed the SMART overall health check. To resolve this fault, replace the drive`


== NetApp HCI 1.8P1
NetApp HCI 1.8P1 includes security and stability improvements.

=== NetApp HCI documentation enhancements
You can now access NetApp HCI upgrading, expansion, monitoring, and concepts information in an easy-to-navigate format link:index.html[here^].

=== NetApp Element Plug-in for vCenter Server 4.5 availability
The NetApp Element Plug-in for vCenter Server 4.5 is available outside of the management node 12.2 and NetApp HCI 1.8P1 releases. To upgrade the plug-in, follow the instructions in the link:concept_hci_upgrade_overview.html[NetApp HCI Upgrades^] documentation.

=== NetApp Hybrid Cloud Control enhancements
NetApp Hybrid Cloud Control is enhanced for version 1.8P1. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[Learn more^].
[discrete]
== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[NetApp Hybrid Cloud Control and Management Services Release Notes^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* http://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element Software Documentation Center for previous versions^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software[Firmware and driver versions for NetApp HCI and NetApp Element software^]



== NetApp Element software
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2873789[NetApp Element Software 12.2 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2865022[NetApp Element Software 12.0 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2864256[NetApp Element Software 11.8 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2861225[NetApp Element Software 11.7 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2863854[NetApp Element Software 11.5.1 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2859857[NetApp Element Software 11.3P1 Release Notes]

== NetApp HCI
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2873790[NetApp HCI 1.8P1 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2865021[NetApp HCI 1.8 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2861226[NetApp HCI 1.7P1 Release Notes]

== Management services
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[Management Services Release Notes]

== NetApp Element Plug-in for vCenter Server
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2874631[vCenter Plug-in 4.6 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2873396[vCenter Plug-in 4.5 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2866569[vCenter Plug-in 4.4 Release Notes]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2856119[vCenter Plug-in 4.3 Release Notes]

== Compute firmware
* link:rn_compute_firmware_2.27.html[Compute Firmware Bundle 2.27 Release Notes (latest)]
* link:rn_firmware_12.2.109.html[Compute Firmware Bundle 12.2.109 Release Notes]

== Storage firmware
* link:rn_storage_firmware_2.27.html[Storage firmware Bundle 2.27 Release Notes (latest)]
* link:rn_H610S_BMC_3.84.07.html[H610S BMC 3.84.07 Release Notes]

////
* link:rn_storage_firmware_2.27.html[Storage firmware 2.27 Release Notes]
////

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
