---
permalink: concepts/concept_solidfire_concepts_protection_domains.html
sidebar: sidebar
keywords: 
summary: 'A protection domain is a node or a set of nodes grouped together such that any part or even all of it might fail, while maintaining data availability. Protection domains enable a storage cluster to heal automatically from the loss of a chassis \(chassis affinity\) or an entire domain \(group of chassis\).'
---
= Protection domains
:icons: font
:imagesdir: ../media/

[.lead]
A protection domain is a node or a set of nodes grouped together such that any part or even all of it might fail, while maintaining data availability. Protection domains enable a storage cluster to heal automatically from the loss of a chassis (chassis affinity) or an entire domain (group of chassis).

A protection domain layout assigns each node to a specific protection domain.

Two different protection domain layouts, called protection domain levels, are supported.

* At the node level, each node is in its own protection domain.
* At the chassis level, only nodes that share a chassis are in the same protection domain.
 ** The chassis level layout is automatically determined from the hardware when the node is added to the cluster.
 ** In a cluster where each node is in a separate chassis, these two levels are functionally identical.

You can manually enable protection domain monitoring using the NetAppElement Configuration extension point in the NetApp Element Plug-in for vCenter Server. You can select a protection domain threshold based on node or chassis domains.

When creating a new cluster, if you are using storage nodes that reside in a shared chassis, you might want to consider designing for chassis-level failure protection using the protection domains feature.
