---
permalink: concepts/concept_solidfire_concepts_synchronous_and_asynchronous_replication.html
sidebar: sidebar
keywords: 
summary: 'For clusters running NetApp Element software, real-time replication enables the quick creation of remote copies of volume data.'
---
= Synchronous and asynchronous replication between clusters
:icons: font
:imagesdir: ../media/

[.lead]
For clusters running NetApp Element software, real-time replication enables the quick creation of remote copies of volume data.

You can pair a storage cluster with up to four other storage clusters. You can replicate volume data synchronously or asynchronously from either cluster in a cluster pair for failover and failback scenarios.

== Synchronous replication

Synchronous replication continuously replicates data from the source cluster to the target cluster and is affected by latency, packet loss, jitter, and bandwidth.

Synchronous replication is appropriate for the following situations:

* Replication of several systems over a short distance
* A disaster recovery site that is geographically local to the source
* Time-sensitive applications and the protection of databases
* Business continuity applications that require the secondary site to act as the primary site when the primary site is down

== Asynchronous replication

Asynchronous replication continuously replicates data from a source cluster to a target cluster without waiting for the acknowledgments from the target cluster. During asynchronous replication, writes are acknowledged to the client (application) after they are committed on the source cluster.

Asynchronous replication is appropriate for the following situations:

* The disaster recovery site is far from the source and the application does not tolerate latencies induced by the network.
* There are bandwidth limitations on the network connecting the source and target clusters.
