---
permalink: concepts/concept_solidfire_concepts_nodes.html
sidebar: sidebar
keywords: what is, node, witness, management node, storage, state, pending, active
summary: 'Nodes are the hardware that is grouped into a cluster to be accessed as block storage or compute resources.'
---
= Nodes
:icons: font
:imagesdir: ../media/

[.lead]
Nodes are hardware or virtual resources that are grouped into a cluster to provide block storage and compute capabilities.

NetApp HCI and Element software defines various node roles for a cluster. The types of node roles are management node, storage node, Fibre Channel nodes, and NetApp HCI Witness Nodes.

== Management node

The management node (sometimes abbreviated as mNode) interacts with a storage cluster to perform management actions, but is not a member of the storage cluster. Management nodes periodically collect information about the cluster through API calls and report this information to Active IQ for remote monitoring (if enabled). Management nodes are also responsible for coordinating software upgrades of the cluster nodes.

The management node is a virtual machine that runs in parallel with one or more Element software-based storage clusters. In addition to upgrades, it is used to provide system services including monitoring and telemetry, manage cluster assets and settings, run system tests and utilities, and enable NetApp Support access for troubleshooting. As of the Element 11.3 release, the management node functions as a microservice host, allowing for quicker updates of select software services outside of major releases. These microservices or management services, such as the Active IQ collector, QoSSIOC for the vCenter Plug-in, and management node service, are updated frequently as service bundles.

== Storage nodes

A SolidFire storage node is a server containing a collection of drives that communicate with each other through the Bond10G network interface. Drives in the node contain block and metadata space for data storage and data management. Each node contains a factory image of NetApp Element software.

Storage nodes have the following characteristics:

* Each node has a unique name. If a node name is not specified by an administrator, it defaults to SF-XXXX, where XXXX is four random characters generated by the system.
* Each node has its own high-performance non-volatile random access memory (NVRAM) write cache to improve overall system performance and reduce write latency.
* Each node is connected to two networks, storage and management, each with two independent links for redundancy and performance. Each node requires an IP address on each network.
* You can create a cluster with new storage nodes, or add storage nodes to an existing cluster to increase storage capacity and performance.
* You can add or remove nodes from the cluster at any time without interrupting service.

== Fibre Channel nodes

SolidFire Fibre Channel nodes provide connectivity to a Fibre Channel switch, which you can connect to Fibre Channel clients. Fibre Channel nodes act as a protocol converter between the Fibre Channel and iSCSI protocols; this enables you to add Fibre Channel connectivity to any new or existing SolidFire cluster.

Fibre Channel nodes have the following characteristics:

* Fibre Channel switches manage the state of the fabric, providing optimized interconnections.
* The traffic between two ports flows through the switches only; it is not transmitted to any other port.
* Failure of a port is isolated and does not affect operation of other ports.
* Multiple pairs of ports can communicate simultaneously in a fabric.

== NetApp HCI storage nodes

NetApp HCI storage nodes are hardware that provide the storage resources for a NetApp HCI system. Drives in the node contain block and metadata space for data storage and data management. Each node contains a factory image of NetApp Element software. NetApp HCI storage nodes can be managed using the NetApp Element Management extension point.


== Witness Nodes
NetApp HCI Witness Nodes are virtual machines that run on compute nodes in parallel with an Element software-based storage cluster. Witness Nodes do not host slice or block services. A Witness Node enables storage cluster availability in the event of a storage node failure. You can manage and upgrade Witness Nodes in the same way as other storage nodes. A storage cluster can have up to four Witness Nodes. Their primary purpose is to ensure that enough cluster nodes exist to form a valid ensemble quorum.

TIP: Learn more about link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_witness_nodes.html[Witness Node resource requirements^] and link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_ip_address.html[Witness Node IP address requirements^].

NOTE: In a two-node storage cluster, a minimum of two Witness Nodes are deployed for redundancy in the event of a Witness Node failure. When the NetApp HCI installation process installs Witness Nodes, a virtual machine template is stored in VMware vCenter that you can use to redeploy a Witness Node in case it is accidentally removed, lost, or corrupted. You can also use the template to redeploy a Witness Node if you need to replace a failed compute node that was hosting the Witness Node. For instructions, see the *Redeploy Witness Nodes for two and three-node storage clusters* section link:https://docs.netapp.com/us-en/hci/docs/task_hci_h410crepl.html[here^].

== Node states of operation

[.lead]
A node can be in one of several states depending on the level of configuration.

* *Available*
+
The node has no associated cluster name and is not yet part of a cluster.

* *Pending*
+
The node is configured and can be added to a designated cluster.
+
Authentication is not required to access the node.

* *Pending Active*
+
The system is in the process of installing compatible Element software on the node. When complete, the node will move to the Active state.

* *Active*
+
The node is participating in a cluster.
+
Authentication is required to modify the node.

In each of these states, some fields are read only.

== Find more information
* https://www.netapp.com/us/media/tr-4823.pdf[NetApp HCI Two-Node Storage Cluster | TR-4823^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* http://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element Software Documentation Center^]
