---
permalink: storage/concept_system_manage_key_external_key_management_api_commands.html
sidebar: sidebar
keywords: 
summary: 'List of all of the APIs available for managing and configuring EKM.'
---
= External Key Management API Commands
:icons: font
:imagesdir: ../media/

[.lead]
List of all of the APIs available for managing and configuring EKM.

Used for establishing a trust relationship between the cluster and external customer-owned servers:

* CreatePublicPrivateKeyPair
* GetClientCertificateSignRequest

Used for defining the specific details of external customer-owned servers:

* CreateKeyServerKmip
* ModifyKeyServerKmip
* DeleteKeyServerKmip
* GetKeyServerKmip
* ListKeyServersKmip
* TestKeyServerKmip

Used for creating and maintaining key providers which manage external key servers:

* CreateKeyProviderKmip
* DeleteKeyProviderKmip
* AddKeyServerToProviderKmip
* RemoveKeyServerFromProviderKmip
* GetKeyProviderKmip
* ListKeyProvidersKmip
* TestKeyProviderKmip

For information about the API methods, see API reference information.

https://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-api/home.html[Managing storage with the Element API]
