---
permalink: storage/concept_intro_custom_protection_domains.html
sidebar: sidebar
<<<<<<< HEAD
keywords: protection domain layout, user-defined custom layout, separate nodes, slices, ensemble, chassis. protection domain
summary: 'You can define a custom protection domain layout, where each node is associated with one and only one custom protection domain. By default, each node is assigned to the same default custom protection domain.'
=======
keywords: Protection Domain layout,user-defined,custom layout
summary: 'You can define a custom Protection Domain layout, where each node is associated with one and only one custom Protection Domain. By default, each node is assigned to the same default custom Protection Domain.'
>>>>>>> 04e69d59ad298db4ab67d5e48aec7d0b91307643
---
= Custom Protection Domains
:icons: font
:imagesdir: ../media/

[.lead]
You can define a custom Protection Domain layout that matches your specific chassis and node layout.

If no custom Protection Domains are assigned:

* Cluster operation is unaffected.
* Custom level is neither tolerant nor resilient.

When you configure custom Protection Domains for a cluster, there are three possible levels of protection, which you can see from the Element web UI dashboard:

* Not protected: The storage cluster is not protected from the failure of one of its custom Protection Domains. To fix this, add additional storage capacity to the cluster or reconfigure the cluster's custom Protection Domains to protect the cluster from possible data loss.
* Fault tolerant: The storage cluster has enough free capacity to prevent data loss after the failure of one of its custom Protection Domains.
* Fault resilient: The storage cluster has enough free capacity to self-heal after the failure of one of its custom Protection Domains. After the healing process has completed, the cluster will be protected from data loss if additional domains were to fail.

If more than one custom Protection Domain is assigned, each subsystem will assign duplicates to separate custom Protection Domains. If this is not possible, it reverts to assigning duplicates to separate nodes. Each subsystem (for example, bins, slices, protocol endpoint providers, and ensemble) does this independently.

You can use the Element UI to link:task_data_protection_configure_custom_protection_domains.html[configure custom Protection Domains^], or you can use the following API methods:

* link:../api/reference_element_api_getprotectiondomainlayout.html[GetProtectionDomainLayout^] - shows which chassis and which custom Protection Domain each node is in.
* link:../api/reference_element_api_setprotectiondomainlayout.html[SetProtectionDomainLayout^] - enables a custom Protection Domain to be assigned to each node.

//Contact NetApp support for further details on using custom Protection Domains.

== Find more information

link:../api/index.html[Manage storage with the Element API^]
