---
permalink: storage/concept_upgrade_update_management_services_for_element_storage_based_installations.html
sidebar: sidebar
keywords: what are management services,Update management services,Upgrade management services
summary: 'As of the management node 11.3 release, the management node functions as a microservice host, allowing for quicker updates of select software services outside of major releases for NetApp HCI and SolidFire all-flash storage. These microservices or management services are updated frequently as service bundles from an online software repository. You can use Hybrid Cloud Control to update management services to the latest version. Alternatively, you can use management services REST APIs that are available from the management node to stay up-to-date.'
---
= Update management services for Element storage-based installations
:icons: font
:imagesdir: ../media/

[.lead]
As of the management node 11.3 release, the management node functions as a microservice host, allowing for quicker updates of select software services outside of major releases for NetApp HCI and SolidFire all-flash storage. These microservices or management services are updated frequently as service bundles from an online software repository. You can use Hybrid Cloud Control to update management services to the latest version. Alternatively, you can use management services REST APIs that are available from the management node to stay up-to-date.

To update your management services as part of an end-to-end Element storage system upgrade, see https://docs.netapp.com/us-en/hci/docs/concept_hci_upgrade_overview.html[Upgrades overview]

To update your management services outside of a major Element storage release, see https://docs.netapp.com/us-en/hci/docs/task_hcc_update_management_services.html[Update management services].
