---
permalink: storage/reference_system_manage_cluster_admins_details.html
sidebar: sidebar
keywords: cluster admin
summary: 'On the Cluster Admins page of the Users tab, you can view the following information.'
---
= Cluster Admins details
:icons: font
:imagesdir: ../media/

[.lead]
On the Cluster Admins page of the Users tab, you can view the following information.

* *ID*
+
Sequential number assigned to the cluster administrator account.

* *Username*
+
The name given to the cluster administrator account when it was created.

* *Access*
+
The user permissions assigned to the user account. Possible values:

 ** read
 ** reporting
 ** nodes
 ** drives
 ** volumes
 ** accounts
 ** clusterAdmins
 ** administrator
*Note:* All permissions are available to the administrator access type.

* *Type*
+
The type of cluster administrator. Possible values:

 ** Cluster
 ** Ldap

* *Attributes*
+
If the cluster administrator account was created using the Element API, this column shows any name-value pairs that were set using that method. See the _NetApp Element Software API Reference Guide_.

*Related information*

https://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-api/home.html[Managing storage with the Element API]
