---
permalink: storage/reference_post_deploy_change_default_ssl_certificate.html
sidebar: sidebar
keywords: ssl certificate, SSL, private key, self-signed, cluster, nodes, user-defined certificate, API, change default certificate, certificate, Element API
summary: 'You can change the default SSL certificate and private key of the storage node in the cluster using the NetApp Element API.'
---

= Change the Element software default SSL certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can change the default SSL certificate and private key of the storage node in the cluster using the NetApp Element API.

When a NetApp Element software cluster is created, the cluster creates a unique self-signed Secure Sockets Layer (SSL) certificate and private key that is used for all HTTPS communication via the Element UI, per-node UI, or APIs. Element software supports self-signed certificates as well as certificates that are issued and verified by a trusted Certificate Authority (CA). Verify that you meet the following requirements:

* You have a unique SSL certificate made for the storage cluster.
* The SSL certificate `commonName` field is the cluster name or short name from the fully qualified domain name (FQDN).
* The `Subject Alternative Name` contains the FQDN of the management virtual IP (MVIP address.
* The SSL certificate does not contain additional FQDNs for other systems.
* The `nslookup [MVIP]` command returns the FQDN. 
* The `nslookup  [FQDN]` command returns the MVIP address.
 

You can use the following API methods to get more information about the default SSL certificate and make changes.

For information about each method, see the link:../api/index.html[NetApp Element Software API Reference].

* *GetSSLCertificate*
+
You can use this method to retrieve information about the currently installed SSL certificate including all certificate details.

* *SetSSLCertificate*
+
You can use this method to set the cluster and per-node SSL certificates to the certificate and private key you supply. The system validates the certificate and private key to prevent an invalid certificate from being applied.

* *RemoveSSLCertificate*
+
This method removes the currently installed SSL certificate and private key. The cluster then generates a new self-signed certificate and private key.

NOTE: The cluster SSL certificate is automatically applied to all new nodes added to the cluster. Any node removed from the cluster reverts to a self-signed certificate and all user-defined certificate and key information is removed from the node.


== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F[What are the requirements around setting custom SSL certificates in Element Software?^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
