---
permalink: storage/reference_system_manage_ldap_details.html
sidebar: sidebar
keywords: 
summary: 'The LDAP page on the Cluster tab provides information about the following settings.'
---
= LDAP details
:icons: font
:imagesdir: ../media/

[.lead]
The LDAP page on the Cluster tab provides information about the following settings.

NOTE: You must enable LDAP to view these LDAP configuration settings.

* *Host Name/IP Address*
+
Address of an LDAP or LDAPS directory server.

* *Auth Type*
+
The user authentication method. Possible values:

 ** Direct Bind
 ** Search And Bind

* *Search Bind DN*
+
A fully qualified DN to log in with to perform an LDAP search for the user (needs bind-level access to the LDAP directory).

* *Search Bind Password*
+
Password used to authenticate access to the LDAP server.

* *User Search Base DN*
+
The base DN of the tree used to start the user search. The system searches the subtree from the specified location.

* *User Search Filter*
+
Enter the following using your domain name:
+
`(&(objectClass=person)(|(sAMAccountName=%USERNAME%)(userPrincipalName=%USERNAME%)))`

* *Group Search Type*
+
Type of search that controls the default group search filter used. Possible values:

 ** Active Directory: Nested membership of all of a user's LDAP groups.
 ** No Groups: No group support.
 ** Member DN: Member DN-style groups (single-level).

* *Group Search Base DN*
+
The base DN of the tree used to start the group search. The system searches the subtree from the specified location.

* *Test User Authentication*
+
After LDAP is configured, use this to test the user name and password authentication for the LDAP server. Enter an account that already exists to test this. The distinguished name and user group information appears, which you can copy for later use when creating cluster administrators.
