---
permalink: storage/reference_system_manage_snmp_snmp_details.html
sidebar: sidebar
keywords: snmp, overview, reference, mib, settings, trap
summary: 'On the SNMP page of the Cluster tab, you can view the following information.'
---
= Learn about SNMP
:icons: font
:imagesdir: ../media/

[.lead]
You can configure Simple Network Management Protocol (SNMP) in your cluster.

You can select an SNMP requestor, select which version of SNMP to use, identify the SNMP User-based Security Model (USM) user, and configure traps to monitor the SolidFire cluster. You can also view and access management information base files.

NOTE: You can use both IPv4 and IPv6 addresses.

== SNMP details

On the SNMP page of the Cluster tab, you can view the following information.

* *SNMP MIBs*
+
The MIB files that are available for you to view or download.

* *General SNMP Settings*
+
You can enable or disable SNMP. After you enable SNMP, you can choose which version to use. If using version 2, you can add requestors, and if using version 3, you can set up USM users.

* *SNMP Trap Settings*
+
You can identify which traps you want to capture. You can set the host, port, and community string for each trap recipient.
