---
permalink: storage/reference_system_manage_nodes_storage_nodes_details.html
sidebar: sidebar
keywords: 
summary: 'On the Nodes page of the Cluster tab, you can view information about nodes such as ID, name, configured IOPs, and role type.'
---
= Node details
:icons: font
:imagesdir: ../media/

[.lead]
On the Nodes page of the Cluster tab, you can view information about nodes such as ID, name, configured IOPs, and role type.

* *Node ID*
+
The system-generated ID for the node.

* *Node Name*
+
The host name for the node.

* *Available 4k IOPS*
+
The IOPS configured for the node.

* *Node Role*
+
The role that the node has in the cluster. Possible values:

 ** Cluster Master: The node that performs cluster-wide administrative tasks and contains the MVIP and SVIP.
 ** Ensemble Node: A node that participates in the cluster. There are either 3 or 5 ensemble nodes depending on cluster size.
 ** Fibre Channel: A node in the cluster.

* *Node Type*
+
The model type of the node.

* *Active Drives*
+
The number of active drives in the node.

* *Management IP*
+
The management IP (MIP) address assigned to node for 1GbE or 10GbE network admin tasks.

* *Cluster IP*
+
The cluster IP (CIP) address assigned to the node used for the communication between nodes in the same cluster.

* *Storage IP*
+
The storage IP (SIP) address assigned to the node used for iSCSI network discovery and all data network traffic.

* *Management VLAN ID*
+
The virtual ID for the management local area network.

* *Storage VLAN ID*
+
The virtual ID for the storage local area network.

* *Version*
+
The version of software running on each node.

* *Replication Port*
+
The port used on nodes for remote replication.

* *Service Tag*
+
The unique service tag number assigned to the node.
