---
permalink: storage/reference_prereq_network_port_requirements.html
sidebar: sidebar
keywords: 
summary: 'You might need to allow the following TCP ports through your datacenter’s edge firewall so that you can manage the system remotely and allow clients outside of your datacenter to connect to resources. Some of these ports might not be required, depending on how you use the system.'
---
= Network port requirements
:icons: font
:imagesdir: ../media/

[.lead]
You might need to allow the following TCP ports through your datacenter's edge firewall so that you can manage the system remotely and allow clients outside of your datacenter to connect to resources. Some of these ports might not be required, depending on how you use the system.

All ports are TCP unless stated otherwise, and should permit bi-directional communications between the NetApp Support Server, management node, and nodes running Element software.

TIP: Enable ICMP between the management node, nodes running Element software, and cluster MVIP.

The following abbreviations are used in the table:

* MIP: Management IP address, a per-node address
* SIP: Storage IP address, a per-node address
* MVIP: Management virtual IP address
* SVIP: Storage virtual IP address

|===
| Source| Destination| Port| Description
a|
iSCSI clients
a|
Storage cluster MVIP
a|
443
a|
(Optional) UI and API access
a|
iSCSI clients
a|
Storage cluster SVIP
a|
3260
a|
Client iSCSI communications
a|
iSCSI clients
a|
Storage node SIP
a|
3260
a|
Client iSCSI communications
a|
Management node
a|
sfsupport.solidfire.com
a|
22
a|
Reverse SSH tunnel for support access
a|
Management node
a|
Storage node MIP
a|
22
a|
SSH access for support
a|
Management node
a|
DNS servers
a|
53 TCP/UDP
a|
DNS lookup
a|
Management node
a|
Storage node MIP
a|
442
a|
UI and API access to storage node and Element software upgrades
a|
Management node
a|
Storage node MVIP
a|
442
a|
UI and API access to storage node and Element software upgrades
a|
Management node
a|
Online software repository:

* https://repo.netapp.com/bintray/api/package
* https://netapp-downloads.bintray.com

a|
443
a|
Management node service upgrades
a|
Management node
a|
monitoring.solidfire.com
a|
443
a|
Storage cluster reporting to Active IQ
a|
Management node
a|
Storage cluster MVIP
a|
443
a|
UI and API access to storage node and Element software upgrades
a|
Management node
a|
repo.netapp.com
a|
443
a|
Provides access to components necessary to install/update on-premises deployment.
a|
Management node
a|
Witness Node
a|
9442
a|
Per-node configuration API service
a|
SNMP server
a|
Storage cluster MVIP
a|
161 UDP
a|
SNMP polling
a|
SNMP server
a|
Storage node MIP
a|
161 UDP
a|
SNMP polling
a|
Storage node MIP
a|
DNS servers
a|
53 TCP/UDP
a|
DNS lookup
a|
Storage node MIP
a|
Management node
a|
80
a|
Element software upgrades
a|
Storage node MIP
a|
S3/Swift endpoint
a|
80
a|
(Optional) HTTP communication to S3/Swift endpoint for backup and recovery
a|
Storage node MIP
a|
NTP server
a|
123 UDP
a|
NTP
a|
Storage node MIP
a|
Management node
a|
162 UDP
a|
(Optional) SNMP traps
a|
Storage node MIP
a|
SNMP server
a|
162 UDP
a|
(Optional) SNMP traps
a|
Storage node MIP
a|
LDAP server
a|
389 TCP/UDP
a|
(Optional) LDAP lookup
a|
Storage node MIP
a|
Remote storage cluster MVIP
a|
443
a|
Remote replication cluster pairing communication
a|
Storage node MIP
a|
Remote storage node MIP
a|
443
a|
Remote replication cluster pairing communication
a|
Storage node MIP
a|
S3/Swift endpoint
a|
443
a|
(Optional) HTTPS communication to S3/Swift endpoint for backup and recovery
a|
Storage node MIP
a|
Management node
a|
10514 TCP/UDP

514 TCP/UDP

a|
Syslog forwarding
a|
Storage node MIP
a|
Syslog server
a|
10514 TCP/UDP

514 TCP/UDP

a|
Syslog forwarding
a|
Storage node MIP
a|
LDAPS server
a|
636 TCP/UDP
a|
LDAPS lookup
a|
Storage node MIP
a|
Remote storage node MIP
a|
2181
a|
Intercluster communication for remote replication
a|
Storage node SIP
a|
S3/Swift endpoint
a|
80
a|
(Optional) HTTP communication to S3/Swift endpoint for backup and recovery
a|
Storage node SIP
a|
S3/Swift endpoint
a|
443
a|
(Optional) HTTPS communication to S3/Swift endpoint for backup and recovery
a|
Storage node SIP
a|
Remote storage node SIP
a|
2181
a|
Intercluster communication for remote replication
a|
Storage node SIP
a|
Storage node SIP
a|
3260
a|
Internode iSCSI
a|
Storage node SIP
a|
Remote storage node SIP
a|
4000 through 4020
a|
Remote replication node-to-node data transfer
a|
Storage node SIP
a|
Compute node SIP
a|
442
a|
Compute node API, configuration and validation, and access to software inventory
a|
System administrator PC
a|
Storage node MIP
a|
80
a|
(NetApp HCI only) Landing page of NetApp Deployment Engine
a|
System administrator PC
a|
Management node
a|
442
a|
HTTPS UI access to management node
a|
System administrator PC
a|
Storage node MIP
a|
442
a|
HTTPS UI and API access to storage node
a|
(NetApp HCI only) Configuration and deployment monitoring in NetApp Deployment Engine
a|
System administrator PC
a|
Management node
a|
443
a|
HTTPS UI and API access to management node
a|
System administrator PC
a|
Storage cluster MVIP
a|
443
a|
HTTPS UI and API access to storage cluster
a|
System administrator PC
a|
Storage node MIP
a|
443
a|
HTTPS storage cluster creation, post-deployment UI access to storage cluster
a|
vCenter Server
a|
Storage cluster MVIP
a|
443
a|
vCenter Plug-in API access
a|
System administrator PC
a|
Witness Node
a|
8080
a|
Witness Node per-node web UI
a|
vCenter Server
a|
Management node
a|
8443
a|
(Optional) vCenter Plug-in QoSSIOC service.
a|
vCenter Server
a|
Storage cluster MVIP
a|
8444
a|
vCenter VASA provider access (VVols only)
a|
vCenter Server
a|
Management node
a|
9443
a|
vCenter Plug-in registration. The port can be closed after registration is complete.
|===
