---
permalink: storage/reference_data_vvol_individual_storage_container_details.html
sidebar: sidebar
keywords: storage container
summary: 'You can view the storage container information for an individual storage container by selecting it from the Storage Containers page on the VVols tab.'
---
= Individual storage container details
:icons: font
:imagesdir: ../media/

[.lead]
You can view the storage container information for an individual storage container by selecting it from the Storage Containers page on the VVols tab.

* *Account ID*
+
The ID of the NetAppElement account associated with the storage container.

* *Name*
+
The name of the storage container.

* *Status*
+
The status of the storage container. Possible values:

 ** Active: The storage container is in use.
 ** Locked: The storage container is locked.

* *Chap Initiator Secret*
+
The unique CHAP secret for the initiator.

* *Chap Target Secret*
+
The unique CHAP secret for the target.

* *Storage Container ID*
+
The UUID of the virtual volume storage container.

* *Protocol Endpoint Type*
+
Indicates the protocol endpoint type (SCSI is the only available protocol).
