---
permalink: storage/task_data_manage_volumes_edit_active_volumes.html
sidebar: sidebar
keywords:
summary: 'You can modify volume attributes such as QoS values, volume size, and the unit of measurement in which byte values are calculated. You can also modify account access for replication usage or to restrict access to the volume.'
---
= Edit active volumes
:icons: font
:imagesdir: ../media/

[.lead]
You can modify volume attributes such as QoS values, volume size, and the unit of measurement in which byte values are calculated. You can also modify account access for replication usage or to restrict access to the volume.

You can resize a volume when there is sufficient space on the cluster under the following conditions:

* Normal operating conditions.
* Volume errors or failures are being reported.
* The volume is being cloned.
* The volume is being resynced.

.Steps
. Select *Management* > *Volumes*.
. In the *Active* window, click the Actions icon for the volume you want to edit.
. Click *Edit*.
. *Optional:* Change the total size of the volume.
+
* You can increase, but not decrease, the size of the volume. You can only resize one volume in a single resizing operation. Garbage collection operations and software upgrades do not interrupt the resizing operation.
* If you are adjusting volume size for replication, you should first increase the size of the volume assigned as the replication target. Then you can resize the source volume. The target volume can be greater or equal in size to the source volume, but it cannot be smaller.

+
The default volume size selection is in GB. You can create volumes using sizes measured in GB or GiB:
* 1GB = 1 000 000 000 bytes
* 1GiB = 1 073 741 824 bytes

. *Optional:* Select a different account access level of one of the following:
 ** Read Only
 ** Read/Write
 ** Locked
 ** Replication Target
. *Optional:* Select the account that should have access to the volume.
+
If the account does not exist, click the *Create Account* link, enter a new account name, and click *Create*. The account is created and associated with the volume.
+
NOTE: If there are more than 50 accounts, the list does not appear. Begin typing and the auto-complete function displays possible values for you to choose.

. *Optional:* To change the selection in *Quality of Service*, do one of the following:
 .. Under *Policy*, you can select an existing QoS policy, if available.
 .. Under *Custom Settings*, set customized minimum, maximum, and burst values for IOPS or use the default QoS values.
+
NOTE: If you are using QoS policies on a volume, you can set custom QoS to remove the QoS policy affiliation with the volume. Custom QoS will override and adjust QoS policy values for volume QoS settings.
+
TIP: When you change IOPS values, you should increment in tens or hundreds. Input values require valid whole numbers.
+
TIP: Configure volumes with an extremely high burst value. This allows the system to process occasional large block sequential workloads more quickly, while still constraining the sustained IOPS for a volume.
. Click *Save Changes*.
