---
permalink: storage/task_data_protection_configure_custom_protection_domains.html
sidebar: sidebar
keywords:
summary: 'You can configure custom protection domains to improve resiliency of the cluster.'
---
= Configure custom protection domains
:icons: font
:imagesdir: ../media/

[.lead]
For Element clusters that contain more than two storage nodes, you can configure custom protection domains for each node. When you configure custom protection domains, you must assign all nodes in the cluster to a domain.

TIP: When you assign protection domains, a data sync between nodes begins, and some cluster operations are unavailable until the data sync completes. After a custom protection domain is configured for a cluster, when you add a new storage node, you cannot add drives for the new node until you assign a protection domain for the node and allow the data sync to complete. Visit the link:../concepts/concept_solidfire_concepts_data_protection.html[protection domains documentation] to learn more about protection domains.

NOTE: For a custom protection domain scheme to be useful for a cluster, all storage nodes within each chassis must be assigned to the same custom protection domain. You need to create as many custom protection domains as is needed for this to be the case.

.Steps

. Click *Cluster* > *Nodes*.
. Click *Configure Protection Domains*.
+
In the resulting window, you can see the currently configured protection domains (if any) as well as protection domain assignments for individual nodes.

. Enter a name for the new custom protection domain, and click *Create*.
+
Repeat this step for all new protection domains you need to create.

. For each node in the *Assign Nodes* list, click the dropdown in the *Protection Domain* column and select a protection domain to assign to that node.
. Click *Configure Protection Domains*.
