---
permalink: storage/task_intro_view_api_activity_in_real_time.html
sidebar: sidebar
keywords: solidfire api, element api, element os, element, viewing the API log, viewing API calls
summary: 'The Element system uses the NetApp Element API as the foundation for its features and functionality. The Element UI enables you to view various types of real-time API activity on the system as you use the interface. With the API log, you can view user-initiated and background system API activity, as well as API calls made on the page you are currently viewing.'
---

= View API activity
:icons: font
:imagesdir: ../media/

[.lead]
The Element system uses the NetApp Element API as the foundation for its features and functionality. The Element UI enables you to view various types of real-time API activity on the system as you use the interface. With the API log, you can view user-initiated and background system API activity, as well as API calls made on the page you are currently viewing.

You can use the API log to identify what API methods are used for certain tasks, and see how to use the API methods and objects to build custom applications.

For information about each method, see link:../api/index.html[Element Software API reference].

. From the Element UI navigation bar, click *API Log*.
. To modify the type of API activity displayed in the API Log window, perform the following steps:
 .. Select *Requests* to display API request traffic.
 .. Select *Responses* to display API response traffic.
 .. Filter the types of API traffic by selecting one of the following:
  *** *User Initiated*: API traffic by your activities during this web UI session.
  *** *Background Polling*: API traffic generated by background system activity.
  *** *Current Page*: API traffic generated by tasks on the page you are currently viewing.

== Interface refresh rate impacted by cluster load

Depending on API response times, the cluster might automatically adjust the data refresh interval for certain portions of the NetApp Element software page you are viewing.

The refresh interval is reset to the default when you reload the page in your browser. You can see the current refresh interval by clicking the cluster name in the upper-right of the page. Note that the interval controls how often API requests are made, not how quickly the data comes back from the server.

When a cluster is under heavy load, it might queue API requests from the Element UI. In rare circumstances, when system response is significantly delayed, such as a slow network connection combined with a busy cluster, you might be logged out of the Element UI if the system does not respond to queued API requests quickly enough. If you are redirected to the logout screen, you can log in again after dismissing any initial browser authentication prompt. Upon returning to the overview page, you might be prompted for cluster credentials if they are not saved by your browser.

== Find more information

* link:../api/index.html[Managing storage with the Element API]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
