---
permalink: storage/task_system_manage_key_set_up_external_key_management.html
sidebar: sidebar
keywords: sign request,certificate authority
summary: 'You can follow these steps and use the Element API methods listed to set up your external key management feature.'
---
= Set up External key management
:icons: font
:imagesdir: ../media/

[.lead]
You can follow these steps and use the Element API methods listed to set up your external key management feature.

.What you'll need
* If you are setting up external key management in combination with software encryption at rest, you have enabled software encryption at rest using the link:api/reference_element_api_createcluster.html[CreateCluster] method on a new cluster that does not contain volumes.

.Steps
. Establish a trust relationship with the External Key Server (EKS).
 .. Create a public/private key pair for the Element cluster that is used to establish a trust relationship with the key server by calling the following API method: `CreatePublicPrivateKeyPair`
 .. Get the certificate sign request (CSR) which the Certification Authority needs to sign. The CSR enables the key server to verify that the Element cluster that will be accessing the keys is authenticated as the Element cluster. Call the following API method: `GetClientCertificateSignRequest`
 .. Use the EKS/Certificate Authority to sign the retrieved CSR. See third-party documentation for more information.
. Create a server and provider on the cluster to communicate with the EKS. A key provider defines where a key should be obtained, and a server defines the specific attributes of the EKS that will be communicated with.
 .. Create a key provider where the key server details will reside by calling the following API method: `CreateKeyProviderKmip`
 .. Create a key server providing the signed certificate and the public key of the Certification Authority by calling the following API methods: `CreateKeyServerKmip``TestKeyServerKmip`
+
If the test fails, verify your server connectivity and configuration. Then repeat the test.

 .. Add the key server into the key provider container by calling the following API methods:
 `AddKeyServerToProviderKmip`
 `TestKeyProviderKmip`
+
If the test fails, verify your server connectivity and configuration. Then repeat the test.
. (For hardware-based encryption at rest) Enable link:concepts/concept_solidfire_element_ug_encryption_at_rest.html[encryption at rest] by providing the ID of the key provider that contains the key server used for storing the keys by calling the following API method: `EnableEncryptionAtRest`
+
NOTE: This enable-encryption-at-rest step is not applicable to software encryption at rest. To enable hardware-based encryption at rest using an external key management configuration, you must enable encryption at rest via the link:api/reference_element_api_enableencryptionatrest.html[API]. Enabling encryption at rest using the existing Element UI button will revert to using internally generated keys.

[discrete]
== Find more information
* link:storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html[Enable and disable encryption for a cluster]
* https://www.netapp.com/data-storage/solidfire/documentation/[NetApp SolidFire Resources Page^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[Documentation for earlier versions of NetApp SolidFire and Element products^]
