---
permalink: storage/task_data_manage_volumes_delete_a_volume.html
sidebar: sidebar
keywords: 
summary: 'You can delete one or more volumes from an Element storage cluster.'
---
= Delete a volume
:icons: font
:imagesdir: ../media/

[.lead]
You can delete one or more volumes from an Element storage cluster.

The system does not immediately purge a deleted volume; the volume remains available for approximately eight hours. If you restore a volume before the system purges it, the volume comes back online and iSCSI connections are restored.

If a volume used to create a snapshot is deleted, its associated snapshots become inactive. When the deleted source volumes are purged, the associated inactive snapshots are also removed from the system.

IMPORTANT: Persistent volumes that are associated with management services are created and assigned to a new account during installation or upgrade. If you are using persistent volumes, do not modify or delete the volumes or their associated account.

. Select *Management* > *Volumes*.
. To delete a single volume, perform the following steps:
 .. Click the Actions icon for the volume you want to delete.
 .. In the resulting menu, click *Delete*.
 .. Confirm the action.

+
The system moves the volume to the *Deleted* area on the *Volumes* page.
. To delete multiple volumes, perform the following steps:
 .. In the list of volumes, check the box next to any volumes you want to delete.
 .. Click *Bulk Actions*.
 .. In the resulting menu, click *Delete*.
 .. Confirm the action.
+
The system moves the volumes to the *Deleted* area on the *Volumes* page.
