---
permalink: storage/task_system_manage_rekey_software_ear_master_key.html
sidebar: sidebar
keywords: element, rekey, encryption at rest, rekey master, replace key
summary: 'You can use the Element API to create a replacement key for your external key management server.'
---
= Rekey software encryption at rest master key
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Element API to create a replacement key for an external key management server. This operation creates a new master key. Master keys are always replaced by new master keys and never duplicated or overwritten.

You might need to rekey as part of one of the following procedures:

* Create a new key as part of a change from internal key management to external key management.
* Create a new key as a reaction to or as protection against a security-related event.

NOTE: This process is asynchronous and returns a response before encryption is enabled. You can use the GetAsyncResult method to poll the system to see when the process has completed.

.What you'll need
* You have enabled software encryption at rest using the link:api/reference_element_api_createcluster.html[CreateCluster] method on a new cluster that does not contain volumes and has no I/O.
* There is an link:storage/task_system_manage_key_set_up_external_key_management.html[established trust relationship] between the SolidFire cluster and the External Key Server (EKS).

.Steps

. ListKeyProvidersKmip and grab key provider ID.
. TestKeyProviderKmip to ensure a connection.
. RekeySoftwareEncryptionAtRestMasterKey using KeyManagementType as external and keyProviderID as the ID number of the key provider from the previous step.
. GetAsyncResult with new configuration (see video).
. GetSoftwareEncryptionatRestInfo to confirm as well.

*Related information*

https://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-api/home.html[Managing storage with the Element API]

link:task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.md#[Enable and disable encryption for a cluster]
