---
permalink: storage/task_data_manage_volumes_clone_a_volume.html
sidebar: sidebar
keywords: 
summary: 'You can create a clone of a single volume or multiple volumes to make a point-in-time copy of the data. When you clone a volume, the system creates a snapshot of the volume and then creates a copy of the data referenced by the snapshot. This is an asynchronous process, and the amount of time the process requires depends on the size of the volume you are cloning and the current cluster load.'
---
= Clone a volume
:icons: font
:imagesdir: ../media/

[.lead]
You can create a clone of a single volume or multiple volumes to make a point-in-time copy of the data. When you clone a volume, the system creates a snapshot of the volume and then creates a copy of the data referenced by the snapshot. This is an asynchronous process, and the amount of time the process requires depends on the size of the volume you are cloning and the current cluster load.

The cluster supports up to two running clone requests per volume at a time and up to eight active volume clone operations at a time. Requests beyond these limits are queued for later processing.

NOTE: Operating systems differ in how they treat cloned volumes. VMware ESXi will treat a cloned volume as a volume copy or snapshot volume. The volume will be an available device to use to create a new datastore. For more information on mounting clone volumes and handling snapshot LUNs, see VMware documentation on https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html[mounting a VMFS datastore copy] and https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html[managing duplicate VMFS datastores].

IMPORTANT: Before you truncate a cloned volume by cloning to a smaller size, ensure that you prepare the partitions so that they fit into the smaller volume.

. Select *Management* > *Volumes*.
. To clone a single volume, perform the following steps:
 .. In the list of volumes on the *Active* page, click the Actions icon for the volume you want to clone.
 .. In the resulting menu, click *Clone*.
 .. In the *Clone Volume* window, enter a volume name for the newly cloned volume.
 .. Select a size and measurement for the volume using the *Volume Size* spin box and list.
+
NOTE: The default volume size selection is in GB. You can create volumes using sizes measured in GB or GiB:

  *** 1GB = 1 000 000 000 bytes
  *** 1GiB = 1 073 741 824 bytes

 .. Select the type of access for the newly cloned volume.
 .. Select an account to associate with the newly cloned volume from the *Account* list.
+
NOTE: You can create an account during this step if you click the *Create Account* link, enter an account name, and click *Create*. The system automatically adds the account to the *Account* list after you create it.
. To clone multiple volumes, perform the following steps:
 .. In the list of volumes on the *Active* page, check the box next to any volumes you want to clone.
 .. Click *Bulk Actions*.
 .. In the resulting menu, select *Clone*.
 .. In the *Clone Multiple Volumes* dialog box, enter a prefix for the cloned volumes in the *New Volume Name Prefix* field.
 .. Select an account to associate with the cloned volumes from the *Account* list.
 .. Select the type of access for the cloned volumes.
. Click *Start Cloning*.
+
NOTE: Increasing the volume size of a clone results in a new volume with additional free space at the end of the volume. Depending on how you use the volume, you might need to extend partitions or create new partitions in the free space to make use of it.
