---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html
sidebar: sidebar
keywords: fips, security, federal information processing standards, 140-2, cluster, create
summary: 'Security is becoming increasingly critical for the deployment of solutions in many customer environments. Federal Information Processing Standards \(FIPS\) are standards for computer security and interoperability. FIPS 140-2 certified encryption for data at rest is a component of the overall security solution.'
---
= Prepare Element cluster for FIPS drives feature
:icons: font
:imagesdir: ../media/

[.lead]
Security is becoming increasingly critical for the deployment of solutions in many customer environments. Federal Information Processing Standards (FIPS) are standards for computer security and interoperability. FIPS 140-2 certified encryption for data at rest is a component of the overall security solution.

To prepare for enabling the FIPS drives feature, you should avoid mixing nodes where some are FIPS drives capable and some are not.

A cluster is considered FIPS drives compliant based on the following conditions:

* All drives are certified as FIPS drives.
* All nodes are FIPS drives nodes.
* Encryption at Rest (EAR) is enabled.
* The FIPS drives feature is enabled. All drives and nodes must be FIPS capable and Encryption at Rest must be enabled in order to enable the FIPS drive feature.