---
permalink: storage/task_data_manage_volumes_create_a_volume.html
sidebar: sidebar
keywords: 
summary: 'You can create a volume and associate the volume with a given account. Every volume must be associated with an account. This association gives the account access to the volume through the iSCSI initiators using the CHAP credentials.'
---
= Create a volume
:icons: font
:imagesdir: ../media/

[.lead]
You can create a volume and associate the volume with a given account. Every volume must be associated with an account. This association gives the account access to the volume through the iSCSI initiators using the CHAP credentials.

You can specify QoS settings for a volume during creation.

. Select *Management* > *Volumes*.
. Click *Create Volume*.
. In the *Create a New Volume* dialog box, enter the *Volume Name*.
. Enter the total size of the volume.
+
NOTE: The default volume size selection is in GB. You can create volumes using sizes measured in GB or GiB:

 ** 1GB = 1 000 000 000 bytes
 ** 1GiB = 1 073 741 824 bytes

. Select a *Block Size* for the volume.
. Click the *Account* drop-down list and select the account that should have access to the volume.
+
If an account does not exist, click the *Create Account* link, enter a new account name, and click *Create*. The account is created and associated with the new volume.
+
NOTE: If there are more than 50 accounts, the list does not appear. Begin typing and the auto-complete function displays possible values for you to choose.

. To set the *Quality of Service*, do one of the following:
 .. Under *Policy*, you can select an existing QoS policy, if available.
 .. Under *Custom Settings*, set customized minimum, maximum, and burst values for IOPS or use the default QoS values.
+
Volumes that have a Max or Burst IOPS value greater than 20,000 IOPS might require high queue depth or multiple sessions to achieve this level of IOPS on a single volume.
. Click *Create Volume*.
