---
permalink: storage/task_data_protection_use_group_snapshots_for_data_protection.html
sidebar: sidebar
keywords: 
summary: 'You can create a group snapshot of a related set of volumes to preserve a point-in-time copy of the metadata for each volume. You can use the group snapshot in the future as a backup or rollback to restore the state of the group of volumes to a previous state.'
---
= Using group snapshots for data protection task
:icons: font
:imagesdir: ../media/

[.lead]
You can create a group snapshot of a related set of volumes to preserve a point-in-time copy of the metadata for each volume. You can use the group snapshot in the future as a backup or rollback to restore the state of the group of volumes to a previous state.

*Related information*

xref:task_data_protection_create_a_group_snapshot.adoc[Creating a group snapshot]

xref:task_data_protection_edit_group_snapshots.adoc[Editing group snapshots]

xref:task_data_protection_edit_members_of_group_snapshot.adoc[Editing members of group snapshot]

xref:task_data_protection_delete_a_group_snapshot.adoc[Deleting a group snapshot]

xref:task_data_protection_roll_back_volumes_to_a_group_snapshot.adoc[Rolling back volumes to a group snapshot]

xref:task_data_protection_clone_multiple_volumes.adoc[Cloning multiple volumes]

xref:task_data_protection_clone_multiple_volumes_from_a_group_snapshot.adoc[Cloning multiple volumes from a group snapshot]
