---
permalink: storage/task_data_manage_accounts_edit_an_account.html
sidebar: sidebar
keywords: 
summary: 'You can edit an account to change the status, change the CHAP secrets, or modify the account name.'
---
= Edit an account
:icons: font
:imagesdir: ../media/

[.lead]
You can edit an account to change the status, change the CHAP secrets, or modify the account name.

Modifying CHAP settings in an account or removing initiators or volumes from an access group can cause initiators to lose access to volumes unexpectedly. To verify that volume access will not be lost unexpectedly, always log out iSCSI sessions that will be affected by an account or access group change, and verify that initiators can reconnect to volumes after any changes to initiator settings and cluster settings have been completed.

IMPORTANT: Persistent volumes that are associated with management services are assigned to a new account that is created during installation or upgrade. If you are using persistent volumes, do not modify or delete their associated account.

. Select *Management* > *Accounts*.
. Click the Actions icon for an account.
. In the resulting menu, select *Edit*.
. Edit the *Username*.
. Click the *Status* drop-down list and select a different status.
+
IMPORTANT: Changing the status to *locked* terminates all iSCSI connections to the account, and the account is no longer accessible. Volumes associated with the account are maintained; however, the volumes are not iSCSI discoverable.

. Under *CHAP Settings*, edit the *Initiator Secret* and *Target Secret* credentials used for node session authentication.
+
NOTE: If you do not change the *CHAP Settings* credentials, they remain the same. If you make the credentials fields blank, the system generates new passwords.

. Click *Save Changes*.
