---
permalink: esds-a/reference_esds_sf_sds_config_file.html
sidebar: sidebar
keywords: element,solidfire esds,hardware components,configuration file
summary: 'Every node has a sf_sds_config.yaml file, which includes the list of hardware that you specify to be consumed by the SolidFire eSDS services. After you replace a drive, you must add the replacement drive information in this file for the node you replaced the drive from. This file is stored in /opt/sf/. This file includes all the information about the drives in the node. You must enter the details of the new drive in this file every time you add a new drive.'
---
= Contents of the sf_sds_config.yaml file
:icons: font
:imagesdir: ../media/

[.lead]
Every node has a sf_sds_config.yaml file, which includes the list of hardware that you specify to be consumed by the SolidFire eSDS services. After you replace a drive, you must add the replacement drive information in this file for the node you replaced the drive from. This file is stored in /opt/sf/. This file includes all the information about the drives in the node. You must enter the details of the new drive in this file every time you add a new drive.

Here are the _required_ contents of the file:

|===
| Key| Default| Type| Description
a|
schemaVersion
a|
"2.0"
a|
String
a|
The schema version number for the file.

a|
network
a|
N/A
a|
List
a|
Allowed values: managementInterface,storageInterface

a|
managementInterface
a|
"team0"
a|
String
a|
The name of the pre-configured, redundant, host OS network interface to use for management and cluster management traffic.
a|
storageInterface
a|
"team1"
a|
String
a|
The name of the pre-configured, redundant, host OS network interface to use for storage network traffic (iSCSI traffic).
a|
dataDrives
a|
N/A
a|
List
a|
The list of host OS paths to physical storage devices being used by SolidFire eSDS. You can specify this as complete paths to the block or NVME devices.The following are supported complete path examples: /dev/disk/by-id/wwn-xxxx-xxxx-EXAMPLE, /dev/disk/by-uuid/nvme-xxxx-xxxxx-EXAMPLE, and /dev/sda1

a|
cacheDevices
a|
N/A
a|
List
a|
The host OS path to the physical device being used as the cache device by SolidFire eSDS. You must specify it as a list entry.The following is an example of a supported complete path: /dev/disk/by-id/nvme-nvme.8086-XXXXXXX-XXXXX-XXXXXX-EXAMPLE

|===
