---
permalink: esds-a/reference_esds_api_links.html
sidebar: sidebar
keywords: element,solidfire esds,api methods,enable maintenance mode,disable maintenance mode,get license key,set license key,create cluster API method
summary: 'Several new APIs have been introduced in Element 12.2 that you can use on SolidFire eSDS clusters.'
---
= Use Element 12.2 APIs on SolidFire eSDS clusters
:icons: font
:imagesdir: ../media/

[.lead]
Several new APIs have been introduced in Element 12.2 that you can use on SolidFire eSDS clusters.

For a comprehensive look at all the Element 12.2 APIs, see https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/home.html[Element 12.2 API Reference].

Here is a list of new APIs in Element 12.2:

* https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-3B45CC91-76DF-4F44-9526-F8676F639D22.html[GetLicenseKey]
* https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-46D07046-2411-463E-8166-15463DC57A9B.html[SetLicenseKey]
* https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-9A224B03-75F9-4288-8F2A-3E2BAD5918B0.html[EnableMaintenanceMode]
* https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-8F87E5ED-FB68-42BD-B6CD-56D6FF8B4F37.html[DisableMaintenanceMode]

The following APIs have been updated to support SolidFire eSDS clusters:

* https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-B4F5FCDC-0101-4ECD-906C-2D67240D7978.html[AddNodes]
* https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-9E105236-EDCF-4613-8504-C6685AF937A5.html[CreateCluster]
+
NOTE: New parameters, OrderNumber, SerialNumber, and enableSoftwareEncryptionAtRest have been added to the CreateCluster method in Element software 12.2. You must specify these parameters while using this API method for creating a cluster after you install SolidFire eSDS.

The following APIs are not supported on SolidFire eSDS clusters:

* ListClusterInterfacePreferences
* ListNodeStats
* DisableSsh
* DisableClusterSsh
* EnableClusterSsh
* EnableSsh
* GetIpmiConfig
* GetIpmiInfo
* GetSshInfo
* ListNetworkInterfaces
* ResetNode
* RestartNetworking
* ResetNetworkConfig
* SetConfig
* SetNetworkConfig
* DisableBmcColdReset
* EnableBmcColdReset
* SetNtpInfo
* TestAddressAvailability

For more information and content related to managing storage using the Element UI and APIs, and Element Plug-in for vCenter Server, see https://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element 12.2 Documentation Center].
