---
permalink: esds-a/task_esds_uninstall.html
sidebar: sidebar
keywords: solidfire esds,uninstalling solidfire esds,ansible role
summary: 'You can “reset” a node on which you installed SolidFire eSDS by removing SolidFire eSDS on the node. To reinstate SolidFire eSDS on the node, you must perform all the installation steps.'
---
= Uninstall SolidFire eSDS on the node
:icons: font
:imagesdir: ../media/

[.lead]
You can "`reset`" a node on which you installed SolidFire eSDS by removing SolidFire eSDS on the node. To reinstate SolidFire eSDS on the node, you must perform all the installation steps.

. Remove drives from the cluster by using the Element UI or the RemoveDrives API method.
+
This results in the system migrating data from the node's drives to other drives in the cluster. The time this process takes is dependent on how much data must be migrated.

. Remove the node from the cluster using either the Element UI or the https://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-api/GUID-905F44D2-9475-4644-B968-7ECCB359DD15.html[RemoveNodes] API method.
. Ping the hosts (nodes) you defined in the inventory file to verify that Ansible can communicate with them.
. Remove SolidFire eSDS from the node as follows:
+
----
yum remove solidfire-element
----

. Remove persistent data from the directory as follows:
+
----
rm -rf /opt/sf
----
