---
permalink: esds-a/task_esds_collect_logs.html
sidebar: sidebar
keywords: solidfire esds,collect logs,netapp hybrid cloud control
summary: 'You can collect logs to send to NetApp Support to help with diagnosing issues with your SolidFire eSDS clusters. You can use the NetApp Hybrid Cloud Control UI for this.'
---
= Collect logs for SolidFire eSDS clusters
:icons: font
:imagesdir: ../media/

[.lead]
You can collect logs to send to NetApp Support to help with diagnosing issues with your SolidFire eSDS clusters. You can use the NetApp Hybrid Cloud Control UI for this.

Keep the following considerations in mind for collecting logs:

* Do not use Podman commands to gather logs.
* NetApp Support uses One Collect for host log collection. For an optimal support experience, you should have installed One Collect.

. Open a web browser and browse to the IP address of the management node. For example:
+
----
https://[management node IP address]
----

. Log in to NetApp Hybrid Cloud Control by providing the storage cluster administrator credentials.
. From the Dashboard, click the menu on the upper right.
. Select *Collect Logs*.
. Select a date range in the *Date Range* drop-down menu to specify what dates the logs should include.
+
If you specify a custom start date, you can select the date to begin the date range. Logs will be collected from that date up to the present time.

. In the *Log Collection* section, select the types of log files the log package should include.
. Click *Collect Logs* to start log collection.
+
Log collection runs in the background, and the page shows the progress.
+
NOTE: Depending on the logs you collect, the progress bar might remain at a certain percentage for several minutes, or progress very slowly at some points.

. Click *Download Logs* to download the log package.
+
The log package is in a compressed UNIX .tgz file format.
