---
permalink: setup/concept_setup_configure_a_storage_node.html
sidebar: sidebar
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI
summary: 'You must configure individual nodes before you can add them to a cluster. After you install and cable a node in a rack unit and power it on, you can configure the node network settings using the per-node UI or the node terminal user interface \(TUI\). Ensure that you have the necessary network configuration information for the node before proceeding.'
---
= Configure a storage node
:icons: font
:imagesdir: ../media/

[.lead]
You must configure individual nodes before you can add them to a cluster. After you install and cable a node in a rack unit and power it on, you can configure the node network settings using the per-node UI or the node terminal user interface (TUI). Ensure that you have the necessary network configuration information for the node before proceeding.

There are two options for configuring storage nodes:



* *Per-node UI*
+
Use the per-node UI (https://<node management IP>:442) to configure node network settings.
+
link:task_configure_the_node_using_the_node_ui.adoc[Configure the storage node using the per-node UI]

+
NOTE: Use the DHCP 1G management IP address displayed in the menu bar at the top of the TUI to access the per-node UI.

* *TUI*
+
Use the node terminal user interface (TUI) to configure the node.

+
link:task_configure_the_node_using_the_tui.adoc[Configure the node using the TUI]

You cannot add a node with DHCP-assigned IP addresses to a cluster. You can use the DHCP IP address to initially configure the node in the per-node UI, TUI, or API. During this initial configuration, you can add static IP address information so that you can add the node to a cluster.

After initial configuration, you can access the node using the node's management IP address. You can then change the node settings, add it to a cluster, or use the node to create a cluster. You can also configure a new node using Element software API methods.

NOTE: Beginning in Element version 11.0, nodes can be configured with IPv4, IPv6, or both addresses for their management network. This applies to both storage nodes and management nodes, except for management node 11.3 and later which does not support IPv6. When you create a cluster, only a single IPv4 or IPv6 address can be used for the MVIP and the corresponding address type must be configured on all nodes.

== Find more information

* link:task_setup_create_a_storage_cluster.adoc[Create a storage cluster]
* link:reference_system_manage_nodes_node_states.adoc[Node states]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
