---
permalink: setup/task_configure_the_node_using_the_tui.html
sidebar: sidebar
keywords: tui, storage node, terminal user interface
summary: 'You can use the terminal user interface \(TUI\) to perform initial configuration for new nodes.'
---
= Configure the node using the TUI
:icons: font
:imagesdir: ../media/

[.lead]
You can use the terminal user interface (TUI) to perform initial configuration for new nodes.

You should configure the Bond1G (Management) and Bond10G (Storage) interfaces for separate subnets. Bond1G and Bond10G interfaces configured for the same subnet causes routing problems when storage traffic is sent via the Bond1G interface. If you must use the same subnet for management and storage traffic, manually configure management traffic to use the Bond10G interface. You can do this for each node using the *Cluster* > *Nodes* page of the Element UI.

.Steps

. Attach a keyboard and monitor to the node and then power on the node.
+
The NetApp Storage Main menu of the TUI appears on the tty1 terminal.
+
NOTE: If the node cannot reach your configuration server, the TUI displays an error message. Check your configuration server connection or the networking connection to resolve the error.

. Select *Network* > *Network Config*.
+
TIP: To navigate through the menu, press the Up or Down arrow keys. To move to another button or to the fields from the buttons, press *Tab*. To navigate between fields, use the Up or Down arrow keys.

. Select *Bond1G (Management)* or *Bond10G (Storage)* to configure the 1G and 10G network settings for the node.
. For the Bond mode and Status fields, press *Tab* to select the Help button and identify the available options.
+
All the nodes in a cluster must have identical cluster names. Cluster names are case-sensitive. If a DHCP server is running on the network with available IP addresses, the 1GbE address appears in the Address field.

. Press *Tab* to select the *OK* button and save the changes.
+
The node is put in a pending state and can be added to an existing cluster or a new cluster.


== For more information
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* link:task_setup_create_a_storage_cluster.adoc[Create a storage cluster]
