---
permalink: setup/task_configure_the_node_using_the_node_ui.html
sidebar: sidebar
keywords: configuring node,configuring node UI
summary: 'You can configure nodes using the per-node user interface.'
---
= Configure the storage node using the per-node UI
:icons: font
:imagesdir: ../media/

[.lead]
You can configure nodes using the per-node user interface.

* You can configure the node to have either an IPv4 or IPv6 address.
* You need the DHCP address displayed in the TUI to access a node. You cannot use DHCP addresses to add a node to a cluster.
+
IMPORTANT: You should configure the management (Bond1G) and storage (Bond10G) interfaces for separate subnets. Bond1G and Bond10G interfaces configured for the same subnet cause routing problems when storage traffic is sent via the Bond1G interface. If you must use the same subnet for management and storage traffic, manually configure management traffic to use the Bond10G interface. You can do this for each node using the *Cluster Settings* page of the per-node UI.

. In a browser window, enter the DHCP IP address of a node.
+
You must add the extension :442 to access the node; for example, https://172.25.103.6:442.
+
The *Network Settings* tab opens with the *Bond1G* section.

.Steps
. Enter the 1G management network settings.
. Click *Apply Changes*.
. Click *Bond10G* to display the 10G storage network settings.
. Enter the 10G storage network settings.
. Click *Apply Changes*.
. Click *Cluster Settings*.
. Enter the hostname for the 10G network.
. Enter the cluster name.
+
IMPORTANT: This name must be added to the configuration for all nodes before a cluster can be created. All the nodes in a cluster must have identical cluster names. Cluster names are case-sensitive.

. Click *Apply Changes*.


== For more information
* link:task_configure_the_node_using_the_tui.adoc[Configure the node using the TUI]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
