---
permalink: setup/task_setup_determine_which_solidfire_components_to_install.html
sidebar: sidebar
keywords: 
summary: 'You might want to check which SolidFire components, such as the management node, Active IQ and the NetApp Monitoring Agent \(NMA\), that you should install, depending on configuration and deployment choices.'
---
= Determining which SolidFire components to install
:icons: font
:imagesdir: ../media/

[.lead]
You might want to check which SolidFire components, such as the management node, Active IQ and the NetApp Monitoring Agent (NMA), that you should install, depending on configuration and deployment choices.

The following table lists the additional components and indicates whether you should install them.

|===
| Component| Standalone SolidFire storage cluster| NetApp HCI cluster
a|
Management node
a|
Recommended
a|
Installed by default, required
a|
Active IQ
a|
Recommended*
a|
Recommended*
a|
NetApp Monitoring Agent
a|
Not supported
a|
Recommended
|===
*Active IQ is required for capacity-licensed SolidFire storage clusters.

. Determine which components should be installed.
. Complete the installation according to the https://docs.netapp.com/us-en/hci/docs/task_mnode_install.html[install the management node] procedure.
+
NOTE: To set up Active IQ, use the --telemetry_active parameter in the setup script to enable data collection for analytics by Active IQ.

. For NetApp Monitoring Agent information, see the deployment information.
+
https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center]
