---
permalink: setup/task_setup_change_the_garbage_collection_constant.html
sidebar: sidebar
keywords:
summary: 'After you create a cluster, you should change the Garbage Collection \(GC\) constant to false to prevent an increase in block space usage. This applies only to NetApp Element software 12.2.'
---
= Change the Garbage Collection constant
:icons: font
:imagesdir: ../media/

[.lead]
After you create a cluster, you should change the Garbage Collection (GC) constant to false to prevent an increase in block space usage. This applies only to NetApp Element software 12.2.

For more information, see https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU437[NetApp Support Bulletin SU437].

.Steps
. Gather the MVIP for your SolidFire cluster that was upgraded to Element software 12.2.
+
This is the IP address you use to connect to the cluster UI web page.

. Substitute that IP address for MVIP in the URL below and paste the link into your web browser:
+
----
https://MVIP/json-rpc/12.2?method=SetConstants&cGCSendBloomFiltersInSeparateThreadEnable=false
----

. After the prompt, enter your cluster admin username and password.
. Note the information in the web page output. The browser displays output similar to the following, withGCSendBloomFiltersInSeparateThreadEnable set to false. You can ignore other cluster constants.
+
----
{"id": null, "result": {cGCSendBloomFiltersInSeparateThreadEnable": false,"requestAPIVersion": "12.2"}}
----

. If you encounter any issues or have questions, contact NetApp Technical Support using the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com].
