---
permalink: esds/task_esds_set_license_key.html
sidebar: sidebar
keywords: solidfire esds,capacity model,license key,set license key
summary: 'When you create a SolidFire eSDS cluster, you need the license key information. NetApp Support will also need the license key information for help with issue resolution. The license key for the SolidFire eSDS cluster consists of the cluster’s order number combined with the serial number, and activates the capacity term license model you have purchased.'
---
= Set license key for SolidFire eSDS
:icons: font
:imagesdir: ../media/

[.lead]
When you create a SolidFire eSDS cluster, you need the license key information. NetApp Support will also need the license key information for help with issue resolution. The license key for the SolidFire eSDS cluster consists of the cluster's order number combined with the serial number, and activates the capacity term license model you have purchased.

You can use the SetLicenseKey method to set the license key for the SolidFire eSDS storage cluster. The SetLicenseKey method has the following input parameters:

|===
| Name| Description| Type| Default value| Required
a|
orderNumber
a|
The new sales order number for this storage cluster.
a|
string
a|
None
a|
Yes
a|
serialNumber
a|
The new serial number for this storage cluster.
a|
string
a|
None
a|
Yes
|===
This method has the following return values:

|===
| Name| Description| Type
a|
orderNumber
a|
The new sales order number of the storage cluster.
a|
string
a|
serialNumber
a|
The new serial number of the storage cluster.
a|
string
|===

. Use the SetLicenseKey API method as shown in the following example:
+
Requests for this method are similar to the following example:
+
----

{
  "method": "SetLicenseKey",
  "params": {
    "orderNumber": "33601",
    "serialNumber": "30G56E3WV"   },
   "id" : 1
}
----
+
This method returns a response similar to the following example:
+
----

{
   "id" : 1,
   "result" : {
      "serialNumber": "30G56E3WV",
      "orderNumber": "33601"
     }
   }
}
----
