---
permalink: api/concept_element_api_ldap_api_methods.html
sidebar: sidebar
keywords: ldap,api,methods
summary: 'You can use the Lightweight Directory Access Protocol \(LDAP\) to authenticate access to Element storage. The LDAP API methods described in this section enable you to configure LDAP access to the storage cluster.'
---
= LDAP API methods
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Lightweight Directory Access Protocol (LDAP) to authenticate access to Element storage. The LDAP API methods described in this section enable you to configure LDAP access to the storage cluster.

* xref:reference_element_api_addldapclusteradmin.adoc[AddLdapClusterAdmin]
* xref:reference_element_api_enableldapauthentication.adoc[EnableLdapAuthentication]
* xref:reference_element_api_disableldapauthentication.adoc[DisableLdapAuthentication]
* xref:reference_element_api_getldapconfiguration.adoc[GetLdapConfiguration]
* xref:reference_element_api_testldapauthentication.adoc[TestLdapAuthentication]

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation/[SolidFire All-Flash Storage Resources page^]
* http://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element Software Documentation Center^]
