---
permalink: api/reference_element_api_createsupportbundle.html
sidebar: sidebar
keywords: create,creating,support,bundle,CreateSupportBundle
summary: 'You can use the CreateSupportBundle to create a support bundle file under the node’s directory. After creation, the bundle is stored on the node as a tar.gz file.'
---
= CreateSupportBundle
:icons: font
:imagesdir: ../media/

[.lead]
You can use the CreateSupportBundle to create a support bundle file under the node's directory. After creation, the bundle is stored on the node as a tar.gz file.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
bundleName
a|
Unique name for the support bundle. If no name is provided, then "supportbundle" and the node name are used as the file name.
a|
string
a|
None
a|
No
a|
extraArgs
a|
This parameter is passed to the sf_make_support_bundle script. This parameter should be used only at the request of NetApp Support.
a|
string
a|
None
a|
No
a|
timeoutSec
a|
The number of seconds the support bundle script runs.
a|
integer
a|
1500
a|
No
|===

== Return values

This method has the following return values:

|===
|Name |Description |Type
a|
details
a|
The details of the support bundle. Possible values:

* bundleName: The name specified in the CreateSupportBundleAPI method. If no name was specified, "supportbundle" is used.
* extraArgs: The arguments passed with this method.
* files: A list of the support bundle files that the system created.
* output: The command line output from the script that created the support bundle.
* timeoutSec: The number of seconds the support bundle script runs before stopping.
* url: URL to the support bundle created.

a|
JSON object
a|
duration
a|
The time used to create the support bundle in the format: HH:MM:SS.ssssss.
a|
string
a|
result
a|
The success or failure of the support bundle operation.
a|
string
|===

== Request example

Requests for this method are similar to the following example:

----
{
 "method": "CreateSupportBundle",
"params": {}
 },
"id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
"id": 1,
"result": {
  "details": {
    "bundleName": "supportbundle",
    "extraArgs": "",
    "files": [
         "supportbundle.SF-D220.tar.gz"
     ],
     "output": "timeout -s KILL 1500s /sf/scripts/sf_make_support_bundle --quiet /tmp/solidfire- dtemp.bYRag7/supportbundle timeout -s KILL 1500s pigz --verbose --fast \"/tmp/solidfire-dtemp.bYRag7/supportbundle.*.tar\" /tmp/solidfire-dtemp.bYRag7/supportbundle.SF-D220.tar to /tmp/solidfire-dtemp.bYRag7/supportbundle.SF-D220.tar.gz Moved '/tmp/solidfire-dtemp.bYRag7/supportbundle.SF-D220.tar.gz' to /tmp/supportbundles",
      "timeoutSec": 1500,
      "url": [
          "https://192.168.130.155:442/config/supportbundles/supportbundle.SF-D220.tar.gz"
      ]
    },
    "duration": "00:00:21.166692",
    "result": "Passed"
  }
}
----

== New since version

9.6
