---
permalink: api/reference_element_api_getremotelogginghosts.html
sidebar: sidebar
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts
summary: 'You can use the GetRemoteLoggingHosts method to get the current list of log servers.'
---
= GetRemoteLoggingHosts
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `GetRemoteLoggingHosts` method to get the current list of log servers.

== Parameters

There are no input parameters for `GetRemoteLoggingHosts`.

== Return value

The `GetRemoteLoggingHosts` method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
remoteHosts
a|
List of IP address, FQDN, and port information about hosts configured to receive forwarded logging information
a|
xref:reference_element_api_loggingserver.adoc[loggingServer] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----

== Response example

This method returns a response similar to the following example:

----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         },
         {
            "host": "syslogs.lab.company.net",
            "port": 514
         }
      ]
   }
}
----

== New since version

Available beginning with ONTAP 9.6.

== Find more information

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingHosts]
