---
permalink: api/reference_element_api_getsoftwareencryptionatrestinfo.html
sidebar: sidebar
keywords: system,security,get,getting,software encryption at rest
summary: 'You can use the GetSoftwareEncryptionAtRestInfo method to get information the cluster uses to encrypt data at rest.'
---
= GetLimits
:icons: font
:imagesdir: ../media/

[.lead]
You can use the GetSoftwareEncryptionAtRestInfo method to get Software Encryption-At-Rest (SEAR) information the cluster uses to encrypt data at rest.

== Parameters
This method has no input parameters.

== Return values
This method has the following return values:

[cols=4*,options="header"]
|===
| Parameter| Description| Type| Optional
| masterKeyInfo| Information about the current SEAR master key.| EncryptionKeyInfo| True|
rekeyMasterKeyAsyncResultID| The async result ID of the current or most recent rekey operation (if any), if it hasn’t been deleted yet. GetAsyncResult output will include a SearRekeyMasterKeyInfo.| integer| True|
state| The current Software Encryption At Rest state. Possible values are `disabled` or `enabled`.| string| False|
version| A version number that is incremented each time SEAR is enabled.| integer| False|

== Request example

Requests for this method are similar to the following example:

----
{
 "method": "getsoftwareencryptionatrestinfo",
 "params": {}
}
----

== Response example

This method returns a response similar to the following example:

----
{
    "rekeyMasterKeyAsyncResultID": 1,
    "state": "abcdefghij",
    "version": 1,
    "masterKeyInfo": {
        "keyProviderID": 1,
        "keyManagementType": "abcdefghij",
        "keyID": "abcdef01-1234-5678-90ab-cdef01234567",
        "keyCreatedTime": "abcdefghij"
    }
}
----

== New since version

12.3
